//
//  AddPresenter.swift
//  CleanTodoList
//
//  Created by 장용범 on 2021/01/21.
//  Copyright (c) 2021 장용범. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPresentationLogic
{
//  func presentSomething(response: Add.Something.Response)
}

class AddPresenter: AddPresentationLogic
{
  weak var viewController: AddDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: Add.Something.Response)
//  {
//    let viewModel = Add.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
