//
//  AddRouter.swift
//  CleanTodoList
//
//  Created by 장용범 on 2021/01/21.
//  Copyright (c) 2021 장용범. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func pop()
}

protocol AddDataPassing
{
  var dataStore: AddDataStore? { get }
}

class AddRouter: NSObject, AddRoutingLogic, AddDataPassing
{
  weak var viewController: AddViewController?
  var dataStore: AddDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: AddViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
    
    func pop() {
        viewController?.navigationController?.popViewController(animated: true)
    }
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AddDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
