//
//  TodoListInteractor.swift
//  CleanTodoList
//
//  Created by 장용범 on 2021/01/21.
//  Copyright (c) 2021 장용범. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListBusinessLogic
{
    func fetchTodoList(request: TodoList.FetchTodoList.Request)
    func selectTodo(request: TodoList.SelectTodo.Request)
}

protocol TodoListDataStore
{
    var todoList: [Todo]? { get set }
    var selectedIndex: Int? { get }
}

class TodoListInteractor: TodoListBusinessLogic, TodoListDataStore
{
    var presenter: TodoListPresentationLogic?
    var worker: TodoListWorker? = TodoListWorker()
    var todoList: [Todo]?
    var selectedIndex: Int?
    
    // MARK: Fetch TodoList
    
    func fetchTodoList(request: TodoList.FetchTodoList.Request) {
        worker = TodoListWorker()
        todoList = worker?.fetchTodoList()
        
        let response = TodoList.FetchTodoList.Response(todos: todoList!)
        presenter?.presentFetchTodoList(response: response)
    }
    
    // MARK: Select Todo
    func selectTodo(request: TodoList.SelectTodo.Request) {
        selectedIndex = request.index
    }
    
}
