//
//  TodoListPresenter.swift
//  CleanTodoList
//
//  Created by 장용범 on 2021/01/21.
//  Copyright (c) 2021 장용범. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoListPresentationLogic
{
    func presentFetchTodoList(response: TodoList.FetchTodoList.Response)
}

class TodoListPresenter: TodoListPresentationLogic
{
    private typealias DisplayedTodo = TodoList.DisplayedTodo
    weak var viewController: TodoListDisplayLogic?
    
    // MARK: Fetch Todo
    
    func presentFetchTodoList(response: TodoList.FetchTodoList.Response) {
        let viewModel = TodoList.FetchTodoList.ViewModel(displayedTodos: response.todos.map { makeDisplayedTodo(from: $0) })
        viewController?.displayFetchTodoList(viewModel: viewModel)
    }
    
    private func makeDisplayedTodo(from todo: Todo) -> DisplayedTodo {
        return DisplayedTodo(title: todo.title, time: todo.time + "⏰")
    }
    
}
