//
//  DetailPresenter.swift
//  CleanTodoList
//
//  Created by 장용범 on 2021/01/21.
//  Copyright (c) 2021 장용범. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentShowTodo(response: Detail.ShowTodo.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Show Todo
  
  func presentShowTodo(response: Detail.ShowTodo.Response)
  {
    let viewModel = Detail.ShowTodo.ViewModel(todo: response.todo)
    viewController?.displayShowTodo(viewModel: viewModel)
  }
}
