//
//  DetailInteractor.swift
//  CleanTodoList
//
//  Created by 장용범 on 2021/01/21.
//  Copyright (c) 2021 장용범. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
  func showTodo(request: Detail.ShowTodo.Request)
}

protocol DetailDataStore
{
  var index: Int? { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
  var presenter: DetailPresentationLogic?
  var worker: DetailWorker? = DetailWorker()
  var index: Int?
  
  // MARK: Show Todo
  
  func showTodo(request: Detail.ShowTodo.Request)
  {
    guard let index = index else { return }
    let todo = worker?.todo(at: index)
    print(todo)
    
    let response = Detail.ShowTodo.Response(todo: todo)
    presenter?.presentShowTodo(response: response)
  }
}
